version: '3'
services:
  axonserver:
    image: axoniq/axonserver:latest
    ports:
      - 8024:8024
      - 8124:8124
    volumes:
      - ./data:/data
    command: --server.port=8024 --server.hostname=0.0.0.0
